from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.linalg import norm
import numpy as np

corpus = [
    'How does Buddy Delivery work', 'How does Buddy Delivery operate',
    'How do you deliver', 'How do you take orders',
    'What is the process of an order', 'Who will deliver the order',
    'Who delivers the food', 'Who are the delivery staff',
    'How does everything exactly work',
    'How fast would the restaurant receive my order',
    "What is Buddy Delivery's on-demand food delivery service",
    'What is a delivery person', 'What is Buddy Delivery',
    'What is the purpose of Buddy Delivery',
    'Information about Buddy Delivery', 'What kind of services do you provide',
    'What services is Buddy Delivery into', 'What services are you onto',
    'Do you deliver food for local restaurants',
    'What can I get at Buddy Delivery', 'What is your company motto',
    'Where do you deliver', 'What is your delivery area',
    'What is your delivery zone', "What's your delivery radius",
    "What's your delivery coverage", 'How big is your delivery area',
    'Do you deliver to my house', 'Do you deliver to my city',
    'Which areas do you deliver to',
    'What regions are delivered to by Buddy Delivery',
    'What areas does Buddy Delivery cover', 'What areas does delivery cover',
    'What cities does Buddy Delivery Service', 'Which cities do you work on',
    'What cities do you operate in', 'What cities is Buddy Delivery in',
    'What states do you deliver in', 'In which countries do you serve',
    "Please tell me where does Buddy Delivery's delivery cover",
    "How can I know about the Buddy Delivery's delivery",
    'How Buddy Delivery delivery works',
    "Is Buddy Delivery's delivery available everywhere",
    'Where other cities are Buddy Delivery stores',
    'Is there any other Buddy Delivery store in this country',
    'Is Buddy Delivery available worldwide', 'Do you ship internationally',
    'Where is this service available', 'Where is Buddy Delivery offered',
    'Is Buddy Delivery an international service',
    'Is Buddy Delivery only in the United States',
    'Will Buddy Delivery come to other cities',
    "Is there anywhere you don't deliver", 'Do you delivery to San Leandro',
    'Do you cover Redwood city', 'Does delivery cover CA',
    'Are you available in China', 'Is delivery available in Burlingame',
    'Are you working with venue in Bay area', 'What are your hours',
    'What are your business hours', 'What are your operating hours',
    'What are your delivery hours', 'What are the opening hours',
    'When do you open', 'When are you open', 'How long are you open',
    'Are you open on Sunday', 'What are the delivery hours for Buddy Delivery',
    'When do you close', 'Are you open all the time', 'Do you work 24-hour',
    'When do you deliver', 'Can you deliver my food even at midnight',
    'is the service available at night', 'When do you start delivering',
    'during night till what time can customers place orders',
    'What times can I order', 'How early can i make an order',
    'I want to know the last time for order',
    'What is the last time to accept an order from customer',
    'Do you provide door delivery round the clock',
    'Do you deliver on public holidays',
    'Are you taking orders on national holidays',
    'Are you providing delivery on sundays', 'What is a group order',
    'How do group orders work', 'What are the requirements for group orders',
    'Are there any group order',
    'Which restaurants near me deliver through Buddy Delivery',
    'How many restaurants are near my location',
    'What restaurants near me can you deliver from',
    'What is the list of Buddy Delivery participating restaurants',
    'Do you deliver from all restaurants in that area',
    'How far away from my locations are the available restaurants',
    'How much distance is covered for food delivery',
    'How far are restaurants that I can order from',
    'Any limit on delivery distance', 'How many restaurants can I choose from',
    'How many restaurants can I order from',
    'What restaurants can I order from', 'Where can i find nearby restaurant',
    'What restaurants are the closest to my house that deliver',
    'What is the Buddy Delivery Delight score',
    'How is Delight score calculated',
    'Does Buddy Delivery accommodate corporate orders',
    'Can my workplace order from Buddy Delivery', 'What is catering order',
    'What is corporate order', 'Is there catering order',
    'Catering facility available', 'Is there corporate order',
    'Do you provide catering service', 'Do you cater large parties',
    'What type of catering your company does',
    'Can you handle a catering service', 'Can you handle bulk orders',
    'Do you deliver to businesses',
    'How does Buddy Delivery calculate when my delivery will arrive',
    'How is delivery time calculated',
    'How does Buddy Delivery estimate arrival',
    "How accurate is Buddy Delivery's delivery time estimate",
    'Are Buddy Delivery delivery time calculations accurate',
    'Is the expected time really correct', 'How does delivery estimates work',
    'How much does it cost to order from Buddy Delivery',
    'How much would it cost me if I were to place an order from Buddy Delivery food delivery',
    'What is the cost to order from Buddy Delivery', 'What are the charges',
    'What is the cost of a meal through Buddy Delivery',
    'How much does an order cost from Buddy Delivery',
    'Are Buddy Delivery meals expensive', 'What do you charge',
    'Is Buddy Delivery expensive',
    'If i order from there what will my cost be', 'What are the surcharges',
    'What fees do you charge for', 'What does your service cost',
    'What are the fees for using the service', 'How much is your service',
    'How much does Buddy Delivery charge',
    'How much do you charge for your service', 'Pricing',
    'Will there be any extra charges that I have to pay', 'Any additional fee',
    'How am I billed', 'What is the delivery charge for Buddy Delivery',
    'What are the delivery policies',
    'Buddy Delivery delivers food at what cost',
    'What is your fee on top of the restaurant price',
    'Do you charge extra for home delivery',
    'Are there any extra delivery charges', 'Is there a delivery fee',
    'Any surcharge for delivery',
    'I would be good to know what is the delivery price', 'Cost of delivery',
    'Is there any costs for shipping', 'Do delivery charges apply',
    'How do you calculate delivery charge',
    'Do I need to pay for delivery charges',
    'How much do items on the menu cost',
    'What are the cost of your menu items',
    'Please tell me if the prices are the same as in restaurant',
    'Do I need to pay taxes when ordering for a tax-exempt organization',
    "How do taxes work if I'm ordering for a tax-exempt organization",
    'What is our tax policy when we order', 'Should I tip my delivery person',
    'What is the tipping etiquette with Buddy Delivery',
    'How much should I tip my delivery person', 'What is your tipping policy',
    'Do you have a tipping policy', 'What is the average tip',
    'What is an appropriate tip for the delivery person',
    'How much is the average tip', 'Can delivery staff receive tips',
    'Do delivery staff expect tips', 'Are tips given to the delivery staff',
    'Are tips required', 'Are tips considered mandatory',
    'Are tips considered optional',
    'Do you automatically include tip on my receipt',
    'Is there a tip automatically added to my total',
    'Are there time delay options for orders', 'What is future order',
    'How many restaurants can I order from at the same time',
    'Can you deliver multiple takeaways',
    'Is there an additional cost for ordering from multiple restaurants at the same time',
    'How many orders can I make', 'Is there a limit of what I can order',
    'Is there a minimum limit for orders',
    'How many different restaurants can I get food from in one delivery',
    'How many orders can you handle at a time',
    'Will I be refunded if the restaurant is out of something',
    'How do you deal with missing stock',
    'Can Buddy Delivery accommodate my allergies',
    'Can Buddy Delivery accommodate my dietary restrictions',
    'Where can I find information for my allergies',
    'Where can I find information for dietary restrictions',
    'Is my food prepared peanut free',
    'Do you have any options for people with food allergies',
    'Are substitutions allowed', 'Are special orders allowed',
    'Does my order come with napkins', 'Does my order come with utensils',
    'Will the restaurant provide me with plastic cutlery',
    'Do you guys have nakpin', 'Can you give me extra forks',
    'Can you give me extra knives', 'Do you guys provide napkin',
    'Do you guys provide fork', 'Will meals be labeled',
    'Will I need an ID to accept delivery',
    'Do I need an ID to receive my order', 'Is ID required at delivery',
    'What are the steps for having my delivery accepted',
    'How do you make sure that order is delivered to correct customer',
    'Can a delivery person refuse delivery of alcohol',
    'What is your alcohol policy regarding alcoholic bevrages',
    'What is restocking fee on alcohol orders',
    'Is there a restocking fee if the order isnt completed',
    'Where do I go to use a special coupon or code',
    'Do you accept online coupons', 'Where do I change my payment info',
    'Where do I enter credit card information', 'Do you offer gift cards',
    'Are there Buddy Delivery gift cards', 'What gift cards might you have',
    'What are Buddy Delivery credits and how can i get them',
    'What are the deals for today', 'Do you offer discounts',
    'Are you giving any discounts', 'Do i get any offer for first order',
    'Do you offer coupons',
    'Will Buddy Delivery be running any promotional offers',
    'Do you offer bonuses for referring a friend',
    'Where can I find points to redeem', 'How often are the promotions offer',
    'Are there any promotional offers', 'Is there a customer loyalty program',
    'What are the steps to creating an account',
    'Where do I go to open an account', 'How many accounts can I have',
    'Can I have a lot of accounts', 'What are the account number limitations',
    'Where do i turn in my feedback', 'Where do i turn in my suggestion',
    'Do you have a comments section for me to leave feedback',
    'Where do I send complaints', 'Where can i submit a complaint',
    'Is there any availability for complaint department',
    'Does Buddy Delivery accept recommendations for a new restaurant',
    'Where can I add a restaurant', 'Where is the tracking option',
    'Can you tell me where to go to check my order status',
    'Where will I find my order status', "What's the status of my delivery",
    'What is the status of my order placed one hour ago',
    'Where can I get my tracking details', 'Is the online tracking available',
    'How does order tracking work', 'How does meal tracker work',
    'Is there a tracking number for my order',
    'Will there be an email confirmation of my order',
    'Will I receive a text message with the completion of my order',
    "I'd like to know where my delivery is at the moment", 'Where is my item',
    'Where is my food', 'Where is my order', 'Where is my stuff',
    "What state's my order in", 'When is my food coming',
    'Is the food i ordered on the way', 'When can I expect delivery',
    'When should I expect my order', 'When should I expect the food',
    'How is my delivery doing', 'how long will it be until the food arrives',
    'How much longer before the food is ready',
    'I would like to know when will my order arrive',
    'When will my order reach',
    'Can you tell me what time my order will be ready',
    'When my order is out for delivery',
    'What time will the food be delivered',
    'What time will my order be here by', 'When will I get my order',
    'How fast can you get here', 'will my order be on time',
    'Is my order in late', 'Did you send the food yet',
    'Can they tell me when the delivery person is coming',
    'Has the delivery person left yet',
    'Has the delivery person already picked up the food',
    'What information do you need from me to track my order',
    'Do you offer tracking',
    'Should I call the restaurant to find out about my order',
    "What's ETA on the order", 'Is my order confirmed', 'Did you get my order',
    'Did you recieve my order', 'Has my order been dispacthed',
    'When does the restaurant start preparing my food',
    'Is the app tracking not working', 'What happened to the order',
    'Did my order go through', 'Is my order still coming',
    'Is my order still in progress',
    'Will I be notified when my order is on the way',
    'Where is my delivery person', 'What is the progress of my order',
    'Am I getting my order fulfilled',
    'Where on the website can I change my order',
    'How much time do I have to change an order',
    'If I change my mind about my order after placing it, can it be changed',
    'Is there a fee for changing delivery date',
    'Is it free to change delivery date', 'Where do I cancel an order',
    'How much time do I have to cancel an order',
    'Do I have to pay for canceled orders', 'What is the cancellation policy',
    'Is there a time limit for order cancellations',
    'Is there a fee for order cancellations', "What's your refund policy",
    'Are there any policies to refund my order',
    'Is there a guarantee for orders', 'is there a warranty for orders',
    'Do you do refunds', 'Do you accept returns',
    'Do you accept returns if service is not good',
    'Do you refund money if the services are not satisfactory',
    'Where can i get the refund', 'When will I have my money back',
    'Who do i contact if my order is messed up', 'What is the return fee',
    'What kind of food options do you have', 'What kind of foods you have',
    'What food does this company deliver',
    'What kind of cuisine options do you have', 'What cuisine do you serve',
    'What kind of things do you deliver',
    'What type of orders you will accept', 'What types of food can I order',
    'Which restaurants do you cover', 'What restaurants do you use',
    'Which restaurants do you feature',
    'Which restaurants are covered in the Buddy Delivery service',
    'How many restaurants are covered in the service',
    'How many restaurants are offered', 'What restaurants use Buddy Delivery',
    'Which restaurants work with Buddy Delivery',
    'What stores offer delivery through Buddy Delivery',
    'How many different restaurants do you work with',
    'Which place is Buddy Delivery working with',
    'How many restaurants do you deliver from',
    'How many restaurants do you have', 'What are my choices for ordering',
    'Who you guys work with', 'Where can I see a list of restaurants',
    'Are there any restaurants open for delivery right now',
    'Where can I order from', 'Is there a list of restaurants on your website',
    "What's the best rated restaurant", 'Where can i get food from',
    'Where is a good place to eat',
    'What type of food orders can i place with your system',
    'Where do you source your food', 'Where do you get your food from',
    'Where can I see your catalog', 'Do you have any recommendations',
    'Where do I start', 'What do you sell', 'What food is available',
    'What food is popular in my area',
    "What's the most popular food people order",
    'Is there any special menu today', 'What are the specials today',
    'How do you categorize restaurants',
    'How many restaurants in SF can I order from',
    'Which restaurant is available in PA',
    'Which restaurant delivers to my location',
    'Which restaurant in NY partners with you',
    'Which restaurants in this area do you deliver to',
    'Which restaurants near me do you work with', 'Do you deliver milk tea',
    'Do you have sandwich', 'Do you deliver mexican food',
    'Do you have Italian food', 'Do you sell korean food', 'Are there drinks',
    'Is there Chinese food', 'Do you cater for vegetarians',
    'Are there vegan options', 'Do you provide pure veg food',
    'Where I can see menu items', 'Do you deliver breakfast',
    'Are the meals gluten free', 'Are the food gluten free',
    'Does the food I order have Gluten in it',
    'Are there gluten free options near me',
    'I just wanted to know if you have the gluten-free option',
    'What is the restaurant with the fatest delivery time',
    'Where are the price mentioned', 'How much does a meal typically cost',
    'Can you please let me know the price list of the items available',
    "What's the available menu", 'Where is the menu', 'Is there a menu',
    'Where can I view the menu for my local area', "What's on the menu",
    'Is menu available on the website', 'What is your cleanliness rating',
    'How can i be assured about the hygiene of the place where my food was cooked',
    'How fresh is your food', 'Is your food healthy', 'Is your food tasty',
    'Do you deliver alcohol', 'Do you deliver drinks as well',
    'Can drinks be delivered', 'Do you serve drinks as well',
    'Do you deliver groceries as well', 'Do you deliver fresh fruit',
    'Previous order', 'Last order', 'What is my order number',
    'Show me what is in the order', 'The order I placed for today',
    "What are the orders I've placed recently",
    'May I know what are my recent orders', 'What did I buy', 'Orders',
    'What is the item recently ordered by me',
    'Where do I find the cost of my order',
    'What was the total price of my order', 'How much did my order cost',
    'Order total', 'How much do I owe for my order', 'Is there a size limit',
    'How large can the order be',
    'Is there any limit to order the quantity of food',
    'How much food can I order', 'Can I order any quantity of food',
    'What is the minimum order', 'How much is the minimum order',
    'Is there a minimum order', 'Is there a maximum order',
    'Is there any minimum bill for door delivery',
    'Do I have to make an order over a certain amount to get delivery',
    'Is there a minimum i have to spend for delivery',
    'What is the smallest order I can make',
    'What is the largest order that you can accept',
    'Will the delivery delivery person come to my door',
    'Will the delivery delivery person call me when he arrives',
    'Will my delivery guy call me when he arrives',
    'Will the delivery person call me when he arrives',
    'Will the delivery person contact me if they get lost',
    'How will the delivery person know what door to drop off to',
    'Do I need to be at home to accept delivery',
    "Do I need to be home when it's delivered", 'What are the delivery options',
    'Is there extra charge if I need to ask the delivery man to come upstairs',
    'Do you deliver to inside the building',
    'What delivery options do you offer',
    'Is there any fast delivery option available', 'Can you hurry',
    'Tell me about free shipping', 'Is shipping free',
    'How long is the standard delivery time',
    'What is the average delivery time',
    'Do you guarantee a certain delivery time', 'Do you always deliver on time',
    'Can you tell the maximum delivery time for food',
    'What is minimum time required for order delivery',
    'Can u deliver the food today', 'What is the delivery time for new orders',
    'What is the waiting time of your Delivery',
    'What is the service time for delivery of food',
    'What is estimated delivery time',
    'Where can I see my estimated delivery time', 'How fast do you deliver',
    'How long it takes for you to deliver the food',
    'How long after I order will my order be delivered',
    'How long does delivery take',
    'How long will it take for my food to arrive', 'How long do I need to wait',
    'How long does my order take to arrive and why',
    'How much longer an order will take', 'How fast will I get my food',
    'Still need how long to deliver my order',
    'How quickly can I get the order delivered',
    'Will my delivered meal arrive hot',
    'Will the food be hot when I receive it', 'Are all orders shipped fresh',
    'Are all items shipped fresh', 'Do you guarantee my food will arrive fresh',
    'Is your service dependable', 'Do you offer hot foods',
    'How do you keep the food hot', 'How do you ensure food is still warm',
    'What will the delivery vehicle look like',
    'How is your delivery vehicle marked',
    'What color is your delivery vehicle',
    'I was wondering what type of car my delivery person would be using',
    'Does Buddy Delivery take phone orders', 'Where do I order',
    'I would like to make an order please,where can I go to do that',
    'Do I have to use an app', 'Can I order from my computer',
    'Is there any other way to order except your website',
    'Do I need to have an account', 'Do i need to register for placing order',
    'Is there a online payment facility', 'Do you accept online payment',
    'Do i have to pay before of after the order', 'When will I pay for food',
    'Should I prepay for scheduled deliveries',
    'Do you charge separetly for delivery',
    'How much change does a delivery person carry',
    'Will the delivery boy pick up the cash from my flower pot',
    'Is cash on delivery available', 'Is COD option available',
    'Is there an option to pay on delivery',
    'What kind of payment options are available',
    'What type of payments are accepted', 'What are the payment options',
    'What are the mode of payments',
    'Do I need to have a credit card to do an order',
    'What forms of payment do you accept',
    'What type of payment can I pay with', 'What you accept for payment',
    'Do you take credit card', 'Do you accept cash',
    'How much time does it take to return my funds for canceled orders',
    'When will my refund be processed', 'When will money be credited back',
    "How can I be sure it's safe to pay by card", 'Is it safe to pay online',
    'is it safe to make online payment', 'Is payment online secured',
    'is your website safe', 'How credible is this site',
    'Does Buddy Delivery keep my credit card information',
    'Where can I get a reciept for my food',
    'What is your website to make orders',
    'What is the website to place orders', 'What is your website',
    'Do you have an app', 'Is mobile app free',
    'What is the name of mobile app',
    'What mobile platforms does Buddy Delivery work on',
    'Does Buddy Delivery work on iOS', 'Where is your FAQ',
    'Do I unpack the food myself', 'Who can work for Buddy Delivery',
    'Are you hiring', 'Are there job openings', "What's your name",
    'Do you have a name', 'Do you get a name', 'Who are you',
    'Who I am talking to', 'Where are you located',
    'Where is your main office located', 'What cities are you located in',
    'Where is your base', 'What is your physical location',
    'What is your location', 'How long has this service been around',
    'How long has Buddy Delivery been in business', 'How old is your company',
    'How do I use Buddy Delivery', 'Can you tell me about your services',
    'I want to find information about Buddy Delivery',
    'I want to know bout Buddy Delivery services',
    'Can I know the working time of them', 'How do I create group order',
    'How do I find the closest restaurant to me with Buddy Delivery',
    'Can I make corporate or catering orders on Buddy Delivery',
    'Can I see a menu with prices', 'Can i tip my delivery person',
    'Can I schedule a future order', 'Can I place an order in advance',
    'Can I make an order in advance',
    'Can I place my order to be delivered at a specific time of the day',
    'Is there any option to place a future food order',
    'Is it possible to schedule orders for the future',
    'Can I order for delivery tomorrow',
    'Can I choose specific date for food delivery',
    'Can I choose specific time for food delivery',
    'How do I set up an order for later',
    'Can i order the food for later delivery', 'May i pay in advance',
    'Is there a way to preorder',
    'Can I order from different restaurants at the same time',
    'can i order more than once per day',
    'Can I list a substitute for an item if it is out of order',
    "How can I confirm this menu's correct", 'How can I report a menu error',
    'How can I specify allergies restrictions',
    'How can I specify dietary restrictions',
    'Can I request food substitutions', 'Can I request special preparations',
    'Can i customize my order', 'Can i specify customizations to my order',
    'How do I request napkins and utensils',
    'Can I see how to label food by restaurant', 'How do I redeem promo codes',
    'Can you help me with getting my 10% promo code to work',
    'How do I use discount code', 'How to use coupon code',
    'How do I edit my payment information', 'How do I change my credit card',
    'How do i enter my payment information',
    "Can I link my visa information with my account so I won't have to type it every time",
    'Can I change the payment option for my order', 'Can I buy gift cards',
    'Can I earn Buddy Delivery credits', 'Can I get a discount for my order',
    'How do I create an account', 'How can i have more than one account',
    'Can I have two accounts',
    'Can I create two accounts on the same name but with different delivery address',
    'How do i give my suggestions', 'How do i give my feedback',
    'How to leave a feedback', 'How can i contact Buddy Delivery',
    'How do I file a complaint', 'How do i raise a complaint',
    'Can I suggest a new restaurant for Buddy Delivery',
    'How do I check my order status', 'I wanted to know the order status',
    'Can I know my tracking number', 'I want to track my order',
    'Is there a way to check my order', 'How can I track my delivery',
    'View my current order', 'Can you help me locate my recent delivery',
    'Check when my delivery will arrive',
    'Could you inform me about my delivery status please',
    'Can you provide me the delivery status',
    'Can you please update the status of my order',
    'I would like to confirm if my order is already on the way',
    'Is there any way to track how long deliveries will take',
    'Can I look up my order on your website',
    'Will you help me follow up on my order',
    'Will you please check on my food',
    'I want to know the whereabouts of my order',
    'how will I know when your the delivery person is here',
    'deliver my order right away', 'How do I know my order has been confirmed',
    "I'm trying to find out if my order got accepted",
    'Please provide an ETA of my order',
    'Can you please give me an update on my order',
    'Trying to locate the delivery person for this delivery',
    'Would you please confirm the delivery time of my order',
    'Can I cancel an order', 'Could you cancel my order',
    'Do dismiss the order', 'Delete this order', 'Remove this order',
    'Is it possible for me to make my order cancelled',
    'Can you cancel the food that I have just ordered',
    'Please tell the delivery person not to deliver', 'Can I change an order',
    'I need to edit my order', 'I need to modify my order',
    'I need to adjust this order', 'Make changes to this order',
    'How can I add to an existing order',
    'I need to modify some items in my order',
    'Am I able to edit items in my order',
    'I accidentally ordered too many things and want to edit the order count',
    'Am I able to change items in my order',
    'I ordered earlier, can I add some items',
    'We also need to add two drinks', 'I wanted to add something',
    'Can I change the delivery method for my order',
    'Can you change the order for me', 'I want to order something different',
    "I'd like to add a note for the delivery person who's coming to my door",
    "I'd like to add a special instruction for my delivery",
    'Can I enter special instructions',
    'Can I please give the deliverer special instructions',
    "Can I change my order after it's been placed", 'How do I amend orders',
    'Can I increase the quantity of order', 'Can I take an item off my bill',
    'I want my order replaced', 'Can I add extra ketchup', 'Can I add fries',
    'I need you to deliver it to a different address',
    'The delivery address needs to be changed',
    'I need to change the delivery address',
    'How do i change a shipping address',
    'Use a different address for the delivery',
    'Change the scheduled delivery time',
    'The order should be delivered at a different time',
    'Pick another delivery time',
    'I want to change the time when the order will be delivered',
    'Deliver the order in a different date and time',
    'The delivery time needs to be changed',
    'The delivery time has to be rescheduled', 'i need to reschudule an order',
    'Can you deliver the order sometime later',
    'If I am unsatisfied with any of my purchases can I return it',
    'I want to get the order refund', 'I wanna have my account refunded',
    'How to get a refund', 'How do I get any compensation',
    'I want to be compensated', 'May I please be refunded',
    'I am requesting you to refund my order', 'Please refund my purchase',
    'Can you please refund the item',
    'Kindly refund the amount which I had given for the order',
    'Please refund difference',
    'Reimburse me with Buddy Delivery credits on my account',
    'Can you reimburse the order amount', 'Please issue a refund',
    'How do I get my money back',
    'I want to have my money back on my account with Buddy Delivery credits',
    'Please refund my order money',
    'Please give me my money back for this order',
    'Please return the money for my order',
    'Can you please issue credit directly to my credit card',
    'Can you recommend something for me', 'Give me your restaurant list',
    'Give me some examples of restaurants you work with',
    'Please show me a list of restaurants near my location',
    'Can you search for restaurants for me', 'Please provide me the stores',
    'How can I find out what restaurants are delivering near me',
    'How can I find out what restaurants I can order from on your website',
    'Am i able to choose the restaurant',
    'Can I get to order from my choice of restaurant',
    'How can I see all the restaurants in north california',
    'Can I order pizza', 'Can I order Chinese food',
    'Would you please recommend a place to order japanese food',
    'Tell me the veg menu', 'Tell me the vegetaran menu',
    'Can you find me the restaurant with the fastest delivery time',
    'Send me the menu', 'Can you give an example of a menu',
    'Can I see the menu', 'Can I see an overview of the menu',
    'Can I order alcohol through Buddy Delivery',
    'Can I access previous orders', 'Can I look at a previous order',
    'View previous orders', 'Display my previous purchases',
    'List all my previous purchases with you',
    'Display a list of all my orders', "I'd like to view recent orders",
    'Can I have a look at my recent orders', 'May i know my recent orders',
    'May I see my recent orders', 'Can you tell me my recent orders',
    'How can I get an order number', 'I want to see all of my orders',
    'How can I see what I ordered', 'Could you please list my orders',
    "Show all the orders I've placed",
    'Could you please remind me of the order that was made',
    'Can I check what orders I just placed', 'How can I see my order history',
    'View history of my orders', 'Check my order history',
    'Show the order history', 'Show overview of orders',
    'Show me everything I have ordered', 'Please read my order back to me',
    'How can I manage my orders', 'Can I see the items',
    'I would like to know the prices of some items',
    'Can I pay for rush delivery', 'Can I expedite a delivery order',
    'How can i get free shipping',
    'Can I trust your workers will not mess with my food',
    'Can I trust your delivery person to deliver my food fresh',
    'Can I contact the delivery guy', 'Can I contact the delivery person',
    'I want to talk to the delivery person',
    'Can you help me contact the delivery person',
    'Will you please pass along the message to my delivery person',
    'How do i recognise your vehicle', 'How do i order',
    'Can I Order food online',
    'Could I order the food on Buddy Delivery website only',
    'Can I Order food by phone', 'I have an order to place, can I do it here',
    'How can I make an order', 'Could you please take my food order',
    'How can I pay my bill', 'How can i pay', 'How may i pay for the order',
    'How to make payment', 'How do I do my payments', 'How can I pay online',
    'May i use cash on delivery', 'Am I able to pay with cash at the door',
    'Can I pay upon delivery', 'How can I pay for the delivery',
    'Can I pay by check', 'Can I pay by money transfer',
    "Can I use Buddy Delivery if I don't have a credit card",
    'Can I pay with Disocver card', 'Can I pay with debit card',
    'Can I use debit card to purchase', 'Can I pay with cash',
    'Can I pay with check', 'Can I use money order to purchase',
    'How can I increase the tip I left', 'How do I change the tipping amount',
    "I'd like to add a tip to my bill please",
    'Could you adjust my tip rate for my delivery',
    'I want to update my phone number for the current order',
    'I need to manage my account details', 'How do I access my credits',
    'How do I find my account', 'Can I change my contact number',
    'Can you show me the account', 'How can I find my receipt',
    'Can I get a receipt for my order', 'Can you send me the receipt',
    'How do I use your website', 'I want to try the service',
    'Please direct me to the website to place an order',
    'Can you give me your web address', 'Kindly link me to the faq',
    'How can I access the FAQ', 'Can I work as a delivery person',
    'How do I become a delivery person', 'How can i work for Buddy Delivery',
    'How do I apply for a job',
    "I want to provide feedback on delivery person's service",
    'how to rate the delivery person servise', 'wanna complain about delivery',
    'I want to complain about a delivery person',
    'i want to give your delivery person service a rating',
    'how to give feedback on delivery',
    'i wish to speak to someone about your delivery person service',
    'Leave some feedback about delivery person', 'Rate delivery person',
    'how to log complaints against delivery', 'Why is your pricing so high',
    'Why does the delivery fee cost more at some restaurants than others',
    'Why am I still asked if I want to tip on top of the delivery fee',
    'What if a restaurant is out of an item',
    "What if the restaurant can't fill my order", 'What if a menu looks wrong',
    'What if I have allergies and dietary restrictions', 'I want to have fork',
    'I want to have knife', 'I want to have silverware in my order',
    'Why would a delivery person refuse delivery of alcohol',
    'What if I have a suggestion or feedback', 'What if i have any complaint',
    "What if a restaurant I like isn't available for Buddy Delivery",
    'I just ordered some food from Buddy Delivery',
    'I did not receive an order confirmation', 'I forgot to add onions',
    'I forgot chili oil', "I don't want the items in this order",
    "I don't want this order", "I don't want to order this anymore",
    'I am not at the same address so I will give you the delivery address',
    'The delivery address is different than it was',
    'I moved so I need to change the delivery address',
    "I'm not at that address", 'The address is wrong',
    'I will not be able to collect the order',
    'I will not be home when the order gets delivered', 'I need a refund',
    'I want a refund for my order', 'I want my delivery fee back',
    'I want reimbursement', "I'd like a refund",
    'I would like the order refunded', 'I would like a credit',
    'I want my money back', 'I need my mony back', 'I demand my money back',
    'I would like full refund back to credit card', 'Please refund my order',
    'I need pasta', 'I need burger in San Jose', 'I like pizza',
    'I like Chinese food', "I don't know my order number",
    'I have an order to place', "What happens if you deliver whilst I'm not in",
    "What if I'm not at home when the delivery man comes by",
    'What if im not at home when the order comes',
    'I need a help with my account', 'I forgot my password',
    'My payment is not successful', 'I am having trouble placing my order',
    'I seem to be unable to place my order',
    "The restaurant does't seem to have a record of my order",
    'I forgot to tip the delivery person', 'I forgot to add a tip',
    'I need a job', 'I am still waiting on my order',
    'I am still waiting on my delivery', "My food didn't arrive",
    "Our food isn't here", "My food didn't come", 'Our food never show up',
    'The delivery guy is taking too long, what happened',
    'The delivery is late', 'The delivery person is late', 'My order is late',
    'why is order taking so long',
    "The deliveryman has not come yet and it's been three hours",
    'The delivery person never arrived',
    'The restaurant has not yet delivered my order',
    "Why i haven't got the items i ordered", "I didn't get my food",
    'i have not recieved my order', "I haven't received my food",
    'My order did not arrive', 'What to do on delivery delay',
    'No one delivered our food', 'The estimated delivery time has passed',
    'I believe that my order is incomplete',
    'There are something missing in my order',
    'There are items missing in my order', 'my order lacks something',
    'my order lack some of the items', "I didn't receive the full order",
    'I did not get my complete order',
    "I didn't get everything I ordered in my delivery. what can be done about that",
    'A food item I ordered was not delivered, how can you help',
    'The delivery person arrived without my some of the item',
    'Half of my order was not delivered', 'Missed half my order',
    'I just received an order with a missing item',
    'Some of the items were delivered incorrectly',
    'I received the wrong order', 'I got the wrong order',
    'I was sent the wrong order', 'You sent the wrong order',
    'I did not get what I asked for',
    'There was a mistake in the purchase delivered',
    'My order is completely wrong', 'There was a delivery error in my order',
    'Some of the food I ordered were incorrect',
    'What if my order gets delivered wrong',
    'My order was delivered incorrectly', 'I receive wrong stuff',
    'My delivery person gave me the wrong order',
    'Some of the side dishes are wrong and I cannot find some of them',
    'I cannot find some of side dishes',
    'Some of the side dishes were not found', 'Wrong sides again!',
    'No sides received', 'Some of my sides were not included',
    'Some of my sides are entirely absent',
    'My order was missing the side dishes',
    'The quality of the food I ordered is poor',
    "What if the food's quality is low",
    'The food which i ordered is poor in quality',
    'Food was below expectations', 'Food did not impress',
    "My order's food quality sucks",
    'The food delivered to me did not taste okay', "My food doesn't taste good",
    'The food delivered is uneatable', 'My food is soggy',
    'Our order is completely messed up', 'I never received my delivery',
    "I didn't receive anything from what I ordered",
    "You didn't deliver me my order at all", 'I got no items from my delivery',
    'My order was never delivered', 'My food was never delivered',
    'My order never arrived', 'The order item was the wrong size',
    'The ordered item was either too large',
    'The ordered item was either too small',
    'The size of the ordered item was incorrect',
    'The size of the order item was wrong',
    'The item is not the size I ordered',
    'The order item was not the correct size',
    'My order was prepared incorrectly',
    'A completely wrong order is delivered', "The food wasn't labeled",
    'Food was overcooked', 'Food was undercooked',
    'The food was not cooked the right amount', "The food wasn't well cooked",
    'The food was cooked too much', 'The food arrived raw',
    'You burnt the damn food!', "My order's item weren't fresh",
    "My order's ingredients weren't fresh", "The food I got wasn't fresh",
    'The ingredients in my order seemed stale', "You didn't use fresh items",
    "You didn't use fresh ingredients",
    "My orders's item or ingredients were spoiled",
    'Delivery had spilled food', 'Delivery had messy food',
    'My delivery was messy', 'The delivery has arrived messy',
    'The food was messy because of irresponsible delivery',
    'The food arrived cold', 'The meal was delivered to me cold',
    'The food was cold while I received',
    'My food is not up to my expectations', 'The delivery person was rude',
    'your delivery person was rude to me', 'My delivery person was rude',
    'Your delivery guy is so arrogant', 'delivery person was unprofessional',
    'I was not happy with the way delivery person treated me',
    "delivery person didn't follow delivery instructions",
    "delivery person didn't follow delivery rules",
    'The delivery guy did not follow instructions again',
    'The instructions were not followed by the delivery guy',
    "delivery person didn't deliver as he was told",
    "delivery person didn't deliver as he should",
    'i was short changed by one of the delivery workers',
    'My delivery person just called with a really bad attitude',
    "I can't call the delivery person", 'I cannot contact the delivery person',
    'I have been unsuccessful in contacting my delivery person',
    "I can't reach the delivery person either",
    "My delivery person doesn't answer my call",
    "My delivery person doesn't answer my text",
    "I haven't heard anything from my delivery person yet",
    'I was double charged how do I correct this',
    'What do i do if i was charged twice',
    'It looks like my credit card was charged twice for this order',
    'I believe you double charged my card for an order',
    'My bill was higher than it was supposed to be',
    'I believe the billing on a previous order was wrong',
    'What if I was charged wrong', 'I was overcharged',
    'I was charged the wrong amount', 'I paid with the wrong credit card',
    'The price of my order was wrong', 'What is the email for technical support',
    'What is the contact number for technical support',
    'What is your customer care number',
    'Where can i find the contact number for technical support',
    'Is there a customer service number I can call',
    'Do you have any support number where I can call',
    'Where is your customer service', 'Where is your customer care team',
    'Where can I find support help', 'When is your technical support available',
    'Is your support service available 24/7',
    'When can I contact your technical support',
    'When can I call your technical support',
    'Who should I call for technical support', 'Who should I contact for help',
    'How can I contact support', 'How can I contact your company',
    'How to connect with the support team',
    'How can I reach your support team', 'How can I reach the sales people',
    'I need to contact your sales team', 'I need to speak to someone for help',
    'Can I talk to someone for help', 'I need to call someone for help',
    'How can I request for support', 'Can I talk to a representive',
    'Can I talk to a customer rep', 'Can I talk with your team',
    'I need to talk to support', 'I need to dicuss with some about this issue',
    'Can I call you guys to ask questions directly',
    'How do I get in touch with the technical support',
    'How do I get in touch with your tech team',
    'Can I get your contact number', 'Can I get technical support at any time',
    'Please give my the contact info of your support team',
    'Please give me your phone number', 'Please send your contact number',
    'Please share one of your contact numbers',
    'Can you give me the email for techincal support',
    'Transfer me to the call center', 'Can you meet us for support',
    'Connect me to your sales team', 'Please call me', 'Please discuss on call',
    'Can you give me a call', 'Please contact me directly', 'Can you reach me',
    'Can you arrange a call', 'I need a response from you guys immediately',
    'I need support', 'I need quick assistance', "I haven't got any reply yet"
]

vect = TfidfVectorizer(min_df=1, stop_words="english")
tfidf = vect.fit_transform(corpus).toarray()
print(tfidf)

result = float('-inf')
index = 0
for i, v in enumerate(tfidf[1:]):
    numerator = np.dot(tfidf[0], v)
    denominator = (norm(tfidf[0]) * norm(v))
    if denominator == 0:
        result = 0
    else:
        result = numerator / denominator
    if result > 0.8:
        print(result)
        print(i)
        print(corpus[i + 1])
